name: example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  animated_text_kit:
    path: ../

flutter:

  uses-material-design: true
